VanLangDoctor/VanLangDoctor/Areas/Admin/Controllers/QL_DonThuocController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using VanLangDoctor.Models;

namespace VanLangDoctor.Areas.Admin.Controllers
{
    public class QL_DonThuocController : Controller
    {
        private CP24Team02Entities db = new CP24Team02Entities();
        private List<DON_THUOC> DonThuoc = null;
        public QL_DonThuocController()
        {
            var session = System.Web.HttpContext.Current.Session;
            if (session["DonThuoc"] != null)
                DonThuoc = session["DonThuoc"] as List<DON_THUOC>;
            else {
                DonThuoc = new List<DON_THUOC>();
                session["DonThuoc"] = DonThuoc;
            }
        }
        
        public ActionResult Index()
        {
            var hashtable = new Hashtable();
            foreach(var donthuoc in DonThuoc)
            {
                if (hashtable[donthuoc.THUOC.ID_THUOC] != null)
                {
                    (hashtable[donthuoc.THUOC.ID_THUOC] as DON_THUOC).CHI_DINH += donthuoc.CHI_DINH;
                }
                else hashtable[donthuoc.THUOC.ID_THUOC] = donthuoc;
            }
            DonThuoc.Clear();
            foreach (DON_THUOC donthuoc in hashtable.Values)
                DonThuoc.Add(donthuoc);
            return View(DonThuoc);
        }
        [HttpPost]
        public ActionResult Create(int ID_Thuoc)
        {
            var thuoc = db.THUOCs.Find(ID_Thuoc);
            DonThuoc.Add(new DON_THUOC
            {
                THUOC = thuoc
            });
            ViewBag.ID_BACSI = new SelectList(db.BACSIs, "ID_BACSI", "TEN_BACSI");
            ViewBag.ID_THUOC = new SelectList(db.THUOCs, "ID_THUOC", "TEN_THUOC");
            TempData["Success"] = "Thêm thành công";
            return RedirectToAction("Index");
        }

        public ActionResult Delete()
        {
            DonThuoc.Clear();
            Session["DonThuoc"] = DonThuoc;
            TempData["Success"] = "Xóa thành công";
            return RedirectToAction("Index");
        }
        /// <summary>
        /// ////////////////////////////////////////////////////////////////////////////////////
        /// </summary>
        
        public ActionResult DS_DonThuoc()
        {
            var model = db.DON_THUOC.ToList();
            return View(model);
        }

        public ActionResult ThemDonThuoc()
        {
            
            ViewBag.Cart = DonThuoc;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThemDonThuoc(DON_THUOC model)
        {
            ValidateDonThuoc(model);
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    model.NGAY_LAP = DateTime.Parse(DateTime.Now.ToString("MM/dd/yyyy HH:mm"));
                    db.DON_THUOC.Add(model);
                    db.SaveChanges();

                    foreach (var item in DonThuoc)
                    {
                        db.DON_THUOC.Add(new DON_THUOC
                        {
                            ID_DON_THUOC = model.ID_DON_THUOC,
                            ID_THUOC = item.THUOC.ID_THUOC
                        });
                    }
                    db.SaveChanges();

                    scope.Complete();
                    Session["DonThuoc"] = null;
                    TempData["Success"] = "Kê đơn thuốc thành công";
                    return RedirectToAction("DS_DonThuoc");
                }
            }
            
            ViewBag.Cart = DonThuoc;
            
            return View(model);
        }

        private void ValidateDonThuoc(DON_THUOC model)
        {
            if (DonThuoc.Count == 0)
                ModelState.AddModelError("", "Chưa có thuốc trong đơn!");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VanLangDoctor/VanLangDoctor/Areas/Admin/Views/QL_DonThuoc/DS_DonThuoc.cshtml
@using VanLangDoctor.Models
@model IEnumerable<VanLangDoctor.Models.DON_THUOC>

@{
    ViewBag.Title = "Danh sách đơn thuốc";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<!-- This page plugin CSS -->
<link href="~/Content/dist-ad/css/style.min.css" rel="stylesheet">
<!-- Custom CSS -->
<div class="page-wrapper" style="display: block">
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-7 align-self-center">
                <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">@ViewBag.Title</h4>
                <div class="d-flex align-items-center">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb m-0 p-0">
                            <li class="breadcrumb-item"><a href="/trang-chu-quan-ly" class="text-muted">Trang chủ</a></li>
                            <li class="breadcrumb-item text-muted active" aria-current="page">@ViewBag.Title</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <div class="col-5 align-self-center">
                <div class="customize-input float-right">
                    <a class="button-plus" href="@Url.Action("Index", "QL_Thuoc")">
                        <span>Trở về</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        @if (TempData["Success"] != null)
                        {
                            <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert" id="successMessage">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true" style=" float: right; margin-top: -10px">×</span>
                                </button>
                                <strong>@TempData["Success"]</strong>
                            </div>
                        }
                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">
                                        <div style="text-align:center">
                                            <h3 class="card-title">Đơn thuốc</h3>
                                        </div>
                                        <div class="container">
                                            <div class="table-responsive">
                                                <table class="table table-bordered">
                                                    <thead>
                                                        <tr class="border-color-red">
                                                            <th scope="col">Chuẩn đoán</th>
                                                            <th scope="col">Chỉ định</th>
                                                            <th scope="col">Lời dặn</th>
                                                            <th scope="col">Ngày lập</th>
                                                            <th scope="col">Thuốc</th>
                                                        </tr>
                                                    </thead>

                                                    @foreach (var item in Model)
                                                    {
                                                    <tr>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.CHUAN_DOAN)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.CHI_DINH)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.LOI_DAN)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.NGAY_LAP)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.THUOC.TEN_THUOC)
                                                        </td>
                                                    
                                                    </tr>
                                                    }
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

VanLangDoctor/VanLangDoctor/Areas/Admin/Views/QL_DonThuoc/Index.cshtml
@model IEnumerable<VanLangDoctor.Models.DON_THUOC>

@{
    ViewBag.Title = "Đơn thuốc đang kê";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<!-- This page plugin CSS -->
<link href="~/Content/dist-ad/css/style.min.css" rel="stylesheet">
<!-- Custom CSS -->
<div class="page-wrapper" style="display: block">
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-7 align-self-center">
                <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">@ViewBag.Title</h4>
                <div class="d-flex align-items-center">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb m-0 p-0">
                            <li class="breadcrumb-item"><a href="/trang-chu-quan-ly" class="text-muted">Trang chủ</a></li>
                            <li class="breadcrumb-item text-muted active" aria-current="page">@ViewBag.Title</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <div class="col-5 align-self-center">
                <div class="customize-input float-right">
                    <a class="button-plus" href="@Url.Action("Index", "QL_Thuoc")">
                        <span>Trở về</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                            @if (TempData["Success"] != null)
                            {
                                <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert" id="successMessage">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true" style=" float: right; margin-top: -10px">×</span>
                                    </button>
                                    <strong>@TempData["Success"]</strong>
                                </div>
                            }
                            <div class="row">
                                <div class="col-12">
                                    <div class="card">
                                        <div class="card-body">
                                            <div style="text-align:center">
                                                <h3 class="card-title">Thuốc</h3>
                                            </div>
                                            <div class="container">
                                                <div class="table-responsive">
                                                    <table class="table table-bordered">
                                                        <thead>
                                                            <tr class="border-color-red">
                                                                <th scope="col">Hình ảnh</th>
                                                                <th scope="col">Tên thuốc</th>
                                                                <th scope="col">Liều lượng</th>
                                                                <th scope="col">Mô tả</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            @foreach (var item in Model)
                                                            {
                                                                <tr>
                                                                    <td class="border-top-0">
                                                                        <img src="@Url.Action("Picture", "QL_Thuoc", new { item.THUOC.ID_THUOC })" alt=" @item.THUOC.ID_THUOC" class="" width="45" height="45">
                                                                    </td>
                                                                    <td class="border-top-0 text-center font-weight-medium text-muted">
                                                                        <a href="@Url.Action("Details","QL_Thuoc", new {id = item.THUOC.ID_THUOC})">
                                                                            @item.THUOC.TEN_THUOC
                                                                        </a>
                                                                    </td>
                                                                    <td class="border-top-0">@item.THUOC.LIEU_LUONG</td>
                                                                    <td class="border-top-0 text-muted font-14">
                                                                        @if (item.THUOC.MO_TA != null && item.THUOC.MO_TA.Length > 75)
                                                                        {
                                                                            @item.THUOC.MO_TA.Substring(0, 75)<span>...</span>
                                                                        }
                                                                        else
                                                                        {
                                                                            @item.THUOC.MO_TA
                                                                        }
                                                                    </td>
                                                                </tr>
                                                            }
                                                        </tbody>
                                                    </table>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-2">
                                                        <a class="button" href="@Url.Action("ThemDonThuoc")">Xác nhận</a>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <a class="button" style="background-color: rgb(157 154 154 / 44%); color: black" href="@Url.Action("Delete","QL_DonThuoc")">Xoá đơn thuốc</a>

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

VanLangDoctor/VanLangDoctor/Areas/Admin/Views/QL_DonThuoc/ThemDonThuoc.cshtml
@using VanLangDoctor.Models
@model VanLangDoctor.Models.DON_THUOC

@{
    ViewBag.Title = "Xác nhận đơn thuốc";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var Cart = ViewBag.Cart as List<DON_THUOC>;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>

<body>
    <div class="page-wrapper" style="display: block;">
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-7 align-self-center">
                    <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">@ViewBag.Title</h4>
                    <div class="d-flex align-items-center">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb m-0 p-0">
                                <li class="breadcrumb-item"><a href="~/trang-chu-quan-ly" class="text-muted">Trang chủ</a></li>
                                <li class="breadcrumb-item"><a href="~/trang-chu-quan-ly/bac-si/danh-sach" class="text-muted">Bác sĩ</a></li>
                                <li class="breadcrumb-item text-muted active" aria-current="page">@ViewBag.Title</li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <div class="col-5 align-self-center">
                    <div class="customize-input float-right">
                        <a class="button-back" href="@Url.Action("Index")">
                            <span-back>Trở về</span-back>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <hr />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="container">
                <div class="row">
                    <div class="form-horizontal col-lg-6">
                        <h2>Thông tin đơn thuốc</h2>
                        
                        <div class="form-group">
                            <label><b>Chuẩn đoán:</b></label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.CHUAN_DOAN, new { htmlAttributes = new { @class = "form-control", @required = true } })
                                @Html.ValidationMessageFor(model => model.CHUAN_DOAN, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label><b>Chỉ định:</b></label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.CHI_DINH, new { htmlAttributes = new { @class = "form-control", @required = true } })
                                @Html.ValidationMessageFor(model => model.CHI_DINH, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label><b>Lời dặn của bác sĩ:</b></label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.LOI_DAN, new { htmlAttributes = new { @class = "form-control" , @required = true } })
                                @Html.ValidationMessageFor(model => model.LOI_DAN, "", new { @class = "text-danger" })
                            </div>
                        </div>
                            @*<div class="form-group">
                                @Html.LabelFor(model => model.ID_BACSI, "ID_BACSI", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("ID_BACSI", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ID_BACSI, "", new { @class = "text-danger" })
                                </div>
                            </div>*@

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Xác nhận" class="button" />
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="order_box">
                            <h2>Thuốc</h2>
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <ul class="list">
                                @foreach (var item in Cart)
                                {
                                    <li>
                                        <a href="@Url.Action("Details", "QL_Thuoc", new {id = item.THUOC.ID_THUOC })">
                                            @item.THUOC.TEN_THUOC
                                            <span class="middle">x @item.THUOC.LIEU_LUONG</span>
                                        </a>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</body>
</html>