VanLangDoctor/VanLangDoctor/Areas/Admin/Controllers/HoSo_BenhAnController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VanLangDoctor.Models;

namespace VanLangDoctor.Areas.Admin.Controllers
{
    public class HoSo_BenhAnController : Controller
    {
        private CP24Team02Entities db = new CP24Team02Entities();

        // GET: Admin/HoSo_BenhAn
        public ActionResult HS_BenhAn()
        {
            var SO_KHAM_BENH = db.SO_KHAM_BENH.Include(b => b.DON_THUOC);
            return View(SO_KHAM_BENH.ToList());
        }

        // GET: Admin/HoSo_BenhAn/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SO_KHAM_BENH SO_KHAM_BENH = db.SO_KHAM_BENH.Find(id);
            if (SO_KHAM_BENH == null)
            {
                return HttpNotFound();
            }
            return View(SO_KHAM_BENH);
        }

        // GET: Admin/HoSo_BenhAn/Create
        public ActionResult Create()
        {
            ViewBag.ID_DON_THUOC = new SelectList(db.DON_THUOC, "ID_DON_THUOC", "CHUAN_DOAN");
            return View();
        }

        // POST: Admin/HoSo_BenhAn/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_SO_KHAM_BENH,KET_QUA,CHUAN_DOAN,TIEN_SU_BENH,GHI_CHU,ID_DON_THUOC")] SO_KHAM_BENH SO_KHAM_BENH)
        {
            if (ModelState.IsValid)
            {
                db.SO_KHAM_BENH.Add(SO_KHAM_BENH);
                db.SaveChanges();
                return RedirectToAction("HS_BenhAn");
            }

            ViewBag.ID_DON_THUOC = new SelectList(db.DON_THUOC, "ID_DON_THUOC", "CHUAN_DOAN", SO_KHAM_BENH.ID_DON_THUOC);
            return View(SO_KHAM_BENH);
        }

        // GET: Admin/HoSo_BenhAn/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SO_KHAM_BENH SO_KHAM_BENH = db.SO_KHAM_BENH.Find(id);
            if (SO_KHAM_BENH == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_DON_THUOC = new SelectList(db.DON_THUOC, "ID_DON_THUOC", "CHUAN_DOAN", SO_KHAM_BENH.ID_DON_THUOC);
            return View(SO_KHAM_BENH);
        }

        // POST: Admin/HoSo_BenhAn/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_SO_KHAM_BENH,KET_QUA,CHUAN_DOAN,TIEN_SU_BENH,GHI_CHU,ID_DON_THUOC")] SO_KHAM_BENH SO_KHAM_BENH)
        {
            if (ModelState.IsValid)
            {
                db.Entry(SO_KHAM_BENH).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("HS_BenhAn");
            }
            ViewBag.ID_DON_THUOC = new SelectList(db.DON_THUOC, "ID_DON_THUOC", "CHUAN_DOAN", SO_KHAM_BENH.ID_DON_THUOC);
            return View(SO_KHAM_BENH);
        }

        // GET: Admin/HoSo_BenhAn/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SO_KHAM_BENH SO_KHAM_BENH = db.SO_KHAM_BENH.Find(id);
            if (SO_KHAM_BENH == null)
            {
                return HttpNotFound();
            }
            return View(SO_KHAM_BENH);
        }

        // POST: Admin/HoSo_BenhAn/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SO_KHAM_BENH SO_KHAM_BENH = db.SO_KHAM_BENH.Find(id);
            db.SO_KHAM_BENH.Remove(SO_KHAM_BENH);
            db.SaveChanges();
            return RedirectToAction("HS_BenhAn");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VanLangDoctor/VanLangDoctor/Areas/Admin/Views/HoSo_BenhAn/Create.cshtml
@model VanLangDoctor.Models.BENH_AN

@{
    ViewBag.Title = "Tạo bệnh án";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/formcrud.css" rel="stylesheet" />
</head>

<body>
    <div class="page-wrapper" style="display: block;">
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-7 align-self-center">
                    <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">@ViewBag.Title</h4>
                    <div class="d-flex align-items-center">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb m-0 p-0">
                                <li class="breadcrumb-item"><a href="~/trang-chu-quan-ly" class="text-muted">Trang chủ</a></li>
                                <li class="breadcrumb-item"><a href="@Url.Action("HS_BenhAn", "HoSo_BenhAn")" class="text-muted">Bệnh Án</a></li>
                                <li class="breadcrumb-item text-muted active" aria-current="page">@ViewBag.Title</li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <div class="col-5 align-self-center">
                    <div class="customize-input float-right">
                        <a class="button-back" href="@Url.Action("HS_BenhAn", "HoSo_BenhAn")">
                            <span-back>Trở về</span-back>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <hr />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="container">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <label><b>Kết quả: </b></label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.KET_QUA, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.KET_QUA, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label><b>Chuẩn đoán: </b></label>
                        <div class="col-md-10">
                            <textarea cols="70" htmlattributes="{ class = form-control }" id="CHUAN_DOAN" name="CHUAN_DOAN" rows="4" style="margin-top: 0px;margin-bottom: 0px;height: auto;border-color: white;box-shadow: 2px 2px 9px -3px;border-radius: 1em 1em 0em;"></textarea>
                            @Html.ValidationMessageFor(model => model.CHUAN_DOAN, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label><b>Tiền sử bệnh: </b></label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TIEN_SU_BENH, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TIEN_SU_BENH, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label><b>Ghi chú: </b></label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.GHI_CHU, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.GHI_CHU, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label><b>Mã đơn thuốc: </b></label>
                        <div class="col-md-10">
                            @Html.DropDownList("ID_DON_THUOC", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ID_DON_THUOC, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="col-md-5">
                        <button type="submit" class="button" style="vertical-align:middle"><span>Thêm mới </span></button>
                    </div>
                </div>
            </div>
        }
    </div>
</body>
</html>
<script src="https://cdn.tiny.cloud/1/o05xhozlmzmedqkqoy70dh2cmo8boru7rhmjurcxygwd5a0h/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: '#CHUAN_DOAN',
        plugins: 'a11ychecker advcode casechange export formatpainter linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tinymcespellchecker',
        toolbar: 'a11ycheck casechange checklist code export formatpainter pageembed permanentpen table',
        toolbar_mode: 'floating',
        tinycomments_mode: 'embedded',
        tinycomments_author: 'Vanlangdoctor',
    });
</script>

VanLangDoctor/VanLangDoctor/Areas/Admin/Views/HoSo_BenhAn/Delete.cshtml
@model VanLangDoctor.Models.BENH_AN

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BENH_AN</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.KET_QUA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KET_QUA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CHUAN_DOAN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CHUAN_DOAN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TIEN_SU_BENH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIEN_SU_BENH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GHI_CHU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GHI_CHU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DON_THUOC.CHUAN_DOAN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DON_THUOC.CHUAN_DOAN)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VanLangDoctor/VanLangDoctor/Areas/Admin/Views/HoSo_BenhAn/Details.cshtml
@model VanLangDoctor.Models.BENH_AN

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>BENH_AN</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.KET_QUA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KET_QUA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CHUAN_DOAN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CHUAN_DOAN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TIEN_SU_BENH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIEN_SU_BENH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GHI_CHU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GHI_CHU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DON_THUOC.CHUAN_DOAN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DON_THUOC.CHUAN_DOAN)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_BENH_AN }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VanLangDoctor/VanLangDoctor/Areas/Admin/Views/HoSo_BenhAn/Edit.cshtml
@model VanLangDoctor.Models.BENH_AN

@{
    ViewBag.Title = "Sửa bệnh án";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/formcrud.css" rel="stylesheet" />
</head>

<body>
    <div class="page-wrapper" style="display: block;">
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-7 align-self-center">
                    <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">@ViewBag.Title</h4>
                    <div class="d-flex align-items-center">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb m-0 p-0">
                                <li class="breadcrumb-item"><a href="~/trang-chu-quan-ly" class="text-muted">Trang chủ</a></li>
                                <li class="breadcrumb-item"><a href="@Url.Action("HS_BenhAn", "HoSo_BenhAn")" class="text-muted">Bệnh Án</a></li>
                                <li class="breadcrumb-item text-muted active" aria-current="page">@ViewBag.Title</li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <div class="col-5 align-self-center">
                    <div class="customize-input float-right">
                        <a class="button-back" href="@Url.Action("HS_BenhAn", "HoSo_BenhAn")">
                            <span-back>Trở về</span-back>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <hr />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="container">
                <div class="form-horizontal">
                    
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID_BENH_AN)

                    <div class="form-group">
                        @Html.LabelFor(model => model.KET_QUA, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.KET_QUA, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.KET_QUA, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CHUAN_DOAN, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CHUAN_DOAN, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CHUAN_DOAN, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TIEN_SU_BENH, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TIEN_SU_BENH, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TIEN_SU_BENH, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.GHI_CHU, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.GHI_CHU, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.GHI_CHU, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ID_DON_THUOC, "ID_DON_THUOC", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("ID_DON_THUOC", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ID_DON_THUOC, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="col-md-5">
                        <button type="submit" class="button" style="vertical-align:middle"><span>Thêm mới </span></button>
                    </div>
                </div>
            </div>

        }
    </div>
</body>
</html>
<script src="https://cdn.tiny.cloud/1/o05xhozlmzmedqkqoy70dh2cmo8boru7rhmjurcxygwd5a0h/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: '#CHUAN_DOAN',
        plugins: 'a11ychecker advcode casechange export formatpainter linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tinymcespellchecker',
        toolbar: 'a11ycheck casechange checklist code export formatpainter pageembed permanentpen table',
        toolbar_mode: 'floating',
        tinycomments_mode: 'embedded',
        tinycomments_author: 'Vanlangdoctor',
    });
</script>

VanLangDoctor/VanLangDoctor/Areas/Admin/Views/HoSo_BenhAn/HS_BenhAn.cshtml
@model IEnumerable<VanLangDoctor.Models.BENH_AN>
@{
    ViewBag.Title = "Bệnh án";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="~/Content/assets-ad/images/favicon.png">
    <title>Adminmart Template - The Ultimate Multipurpose admin template</title>
    <!-- This page plugin CSS -->
    <link href="~/Content/assets-ad/extra-libs/datatables.net-bs4/css/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Content/dist-ad/css/style.min.css" rel="stylesheet">
    <link href="~/Content/formcrud.css" rel="stylesheet" />

</head>

<body>
    <div class="page-wrapper">
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-7 align-self-center">
                    <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">@ViewBag.Title</h4>
                    <div class="d-flex align-items-center">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb m-0 p-0">
                                <li class="breadcrumb-item"><a href="index.html" class="text-muted">Trang chủ</a></li>
                                <li class="breadcrumb-item text-muted active" aria-current="page">@ViewBag.Title</li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <div class="col-5 align-self-center">
                    <div class="customize-input float-right">
                        <a class="button-plus" href="@Url.Action("Create", "HoSo_BenhAn")">
                            <span>Thêm bệnh án</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="zero_config" class="table table-striped table-bordered no-wrap">
                                    <thead>
                                        <tr>
                                            <th>Mã bệnh án</th>
                                            <th>Chuẩn đoán</th>
                                            <th>Kết quả</th>
                                            <th>Tiền sử bệnh</th>
                                            <th>Ghi chú</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td><a href="@Url.Action("Edit","HoSo_BenhAn", new { id = item.ID_BENH_AN })">@item.ID_BENH_AN</a></td>
                                                <td>
                                                    @if (item.CHUAN_DOAN != null && item.CHUAN_DOAN.Length > 100)
                                                    {
                                                        @item.CHUAN_DOAN.Substring(0, 100)
                                                    }
                                                    else
                                                    {
                                                        @MvcHtmlString.Create(item.CHUAN_DOAN)
                                                    }
                                                </td>
                                                <td>@item.KET_QUA</td>
                                                <td>@item.TIEN_SU_BENH</td>
                                                <td>@item.GHI_CHU</td>
                                                <td>
                                                    <a href="@Url.Action("Edit","BENH_AN", new { id = item.ID_BENH_AN })"><i class="ti-settings"></i></a>
                                                    <a href="@Url.Action("Delete","BENH_AN", new { id = item.ID_BENH_AN })"><i class="ti-trash"></i></a>
                                                </td>
                                            </tr>
                                        }

                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>Mã bệnh án</th>
                                            <th>Chuẩn đoán</th>
                                            <th>Kết quả</th>
                                            <th>Tiền sử bệnh</th>
                                            <th>Ghi chú</th>
                                            <th></th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>