VanLangDoctor/VanLangDoctor/Models/THUOC.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLangDoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THUOC()
        {
            this.DON_THUOC = new HashSet<DON_THUOC>();
        }
    
        public int ID_THUOC { get; set; }
        public string TEN_THUOC { get; set; }
        public string LIEU_LUONG { get; set; }
        public string MO_TA { get; set; }
        public string HINH_ANH { get; set; }
        public Nullable<int> ID_NSX { get; set; }
        public Nullable<int> ID_DANHMUC { get; set; }
    
        public virtual DANH_MUC_THUOC DANH_MUC_THUOC { get; set; }
        public virtual NHA_SAN_XUAT NHA_SAN_XUAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DON_THUOC> DON_THUOC { get; set; }
    }
}

VanLangDoctor/VanLangDoctor/Areas/User/Controllers/ThuocController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VanLangDoctor.Models;

namespace VanLangDoctor.Areas.User.Controllers
{
    public class ThuocController : Controller
    {
        private CP24Team02Entities db = new CP24Team02Entities();

        // GET: User/Thuoc
        public ActionResult Medicine()
        {
            var tHUOCs = db.THUOCs.Include(t => t.NHA_SAN_XUAT);
            return View(tHUOCs.ToList());
        }

        // GET: User/Thuoc/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            THUOC tHUOC = db.THUOCs.Find(id);
            if (tHUOC == null)
            {
                return HttpNotFound();
            }
            return View(tHUOC);
        }

        private const string PICTURE_PATH = "~/Content/IMG_MEDICINE/";

        public ActionResult Picture(int ID_Thuoc)
        {
            var path = Server.MapPath(PICTURE_PATH);
            return File(path + ID_Thuoc, "images");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VanLangDoctor/VanLangDoctor/Areas/User/Views/Thuoc/Details.cshtml
@model VanLangDoctor.Models.THUOC

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/User/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>THUOC</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TEN_THUOC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TEN_THUOC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LIEU_LUONG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LIEU_LUONG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MO_TA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MO_TA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HINH_ANH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HINH_ANH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NHA_SAN_XUAT.TEN_NSX)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NHA_SAN_XUAT.TEN_NSX)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_THUOC }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VanLangDoctor/VanLangDoctor/Areas/User/Views/Thuoc/Medicine.cshtml
@model IEnumerable<VanLangDoctor.Models.THUOC>

@{ 
    Layout = "~/Areas/User/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/Content/assets_Medicine/nicepage.css" media="screen">
<link rel="stylesheet" href="~/Content/assets_Medicine/ProductList.css" media="screen">


<section class="u-clearfix u-section-1" id="carousel_df7d">
    <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
        <div class="u-expanded-width u-list u-list-1">
            <div class="u-repeater u-repeater-1">
                @foreach(var a in Model)
            {
                <div class="u-align-center u-container-style u-list-item u-repeater-item">
                    <div class="u-container-layout u-similar-container u-valign-top u-container-layout-1">
                        <img src="@Url.Action("Picture", new {id = a.ID_THUOC})" alt="" class="u-expanded-width u-image u-image-default u-image-1" data-image-width="1000" data-image-height="1500">
                        <a href="@Url.Action("Details", "Thuoc", new { id = a.ID_THUOC})" class="u-btn u-button-style u-palette-4-base u-btn-1">Xem Chi Tiết</a>
                        <p class="u-text u-text-1">Sample text. Click to select the text box. Click again or double click to start editing the text.</p>
                    </div>
                </div>
            }
            </div>
        </div>
    </div>
</section>
<script class="u-script" type="text/javascript" src="~/Content/assets_Medicine/jquery.js" defer=""></script>
<script class="u-script" type="text/javascript" src="~/Content/assets_Medicine/nicepage.js" defer=""></script>