VanLangDoctor/VanLangDoctor/Areas/Admin/Controllers/QL_TinTucController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using VanLangDoctor.Models;

namespace VanLangDoctor.Areas.Admin.Controllers
{
    public class QL_TinTucController : Controller
    {
        private CP24Team02Entities db = new CP24Team02Entities();

        // GET: Admin/QL_TinTuc
        public ActionResult Index()
        {
            return View(db.TIN_TUC.ToList());
        }

        // GET: Admin/QL_TinTuc/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TIN_TUC tIN_TUC = db.TIN_TUC.Find(id);
            if (tIN_TUC == null)
            {
                return HttpNotFound();
            }
            return View(tIN_TUC);
        }

        private const string PICTURE_PATH = "~/Content/IMG_NEWS/";

        public ActionResult Picture(int ID_Tin_Tuc)
        {
            var path = Server.MapPath(PICTURE_PATH);
            return File(path + ID_Tin_Tuc, "images");
        }

        // GET: Admin/QL_TinTuc/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/QL_TinTuc/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TIN_TUC tIN_TUC, HttpPostedFileBase picture)
        {
            if (ModelState.IsValid)
            {
                if (picture != null)
                {
                    using (var scope = new TransactionScope())
                    {
                        tIN_TUC.NGAY_DANG = DateTime.Now;
                        db.TIN_TUC.Add(tIN_TUC);
                        db.SaveChanges();

                        var path = Server.MapPath(PICTURE_PATH);
                        picture.SaveAs(path + tIN_TUC.ID_TIN_TUC);

                        scope.Complete();
                    }
                }
                else ModelState.AddModelError("", "Hình ảnh không được tìm thấy.");
            }
            TempData["Success"] = "Thêm tin mới thành công";
            return RedirectToAction("Index");
        }

        // GET: Admin/QL_TinTuc/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TIN_TUC tIN_TUC = db.TIN_TUC.Find(id);
            if (tIN_TUC == null)
            {
                return HttpNotFound();
            }
            return View(tIN_TUC);
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TIN_TUC tIN_TUC, HttpPostedFileBase picture)
        {
            if (ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    using (var scope = new TransactionScope())
                    {
                        db.Entry(tIN_TUC).State = EntityState.Modified;
                        db.SaveChanges();

                        if (picture != null)
                        {
                            var path = Server.MapPath(PICTURE_PATH);
                            picture.SaveAs(path + tIN_TUC.ID_TIN_TUC);
                        }

                        scope.Complete();
                        TempData["Success"] = "Cập nhật tin thành công";
                        return RedirectToAction("Index");
                    }
                }
                db.Entry(tIN_TUC).State = EntityState.Modified;
            }
            return View(tIN_TUC);
        }

        // GET: Admin/QL_TinTuc/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TIN_TUC tIN_TUC = db.TIN_TUC.Find(id);
            if (tIN_TUC == null)
            {
                return HttpNotFound();
            }
            return View(tIN_TUC);
        }

        // POST: Admin/QL_TinTuc/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TIN_TUC tIN_TUC = db.TIN_TUC.Find(id);
            db.TIN_TUC.Remove(tIN_TUC);
            db.SaveChanges();
            TempData["Success"] = "Xóa tin thành công";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VanLangDoctor/VanLangDoctor/Areas/Admin/Views/QL_TinTuc/Create.cshtml
@model VanLangDoctor.Models.TIN_TUC

@{
    ViewBag.Title = "Thêm tin mới";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div id="main-wrapper" data-theme="light" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
     data-sidebar-position="fixed" data-header-position="fixed" data-boxed-layout="full">

    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-7 align-self-center">
                    <h3 class="page-title text-truncate text-dark font-weight-medium mb-1">@ViewBag.Title</h3>
                    <div class="d-flex align-items-center">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb m-0 p-0">
                                <li class="breadcrumb-item"><a href="~/trang-chu-quan-ly" class="text-muted">Trang chủ</a></li>
                                <li class="breadcrumb-item"><a href="@Url.Action("Index")" class="text-muted">Tin tức</a></li>
                                <li class="breadcrumb-item text-muted active" aria-current="page">@ViewBag.Title</li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <div class="col-5 align-self-center">
                    <div class="customize-input float-right">
                        <a class="button-back" href="@Url.Action("Index")">
                            <span-back>Trở về</span-back>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <hr />
        <div class="container-fluid">
            <div class="container">
                @using (Html.BeginForm("Create", "QL_TinTuc", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <label for="ten_bai_viet"><b>Tiêu đề bài viết</b></label>
                        <div class="form-actions no-color">
                            @Html.EditorFor(model => model.TEN_BAI_VIET, new { htmlAttributes = new { @class = "form-control", @maxlength = "50", @placeholder = "Tiêu đề chứa tối đa 50 ký tự"} })
                            @Html.ValidationMessageFor(model => model.TEN_BAI_VIET, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        <label for="noi_dung"><b>Nội dung</b></label>
                        <div class="form-actions no-color">
                            @Html.TextAreaFor(m => m.NOI_DUNG, new { @class = "form-control", @id = "area1", @name = "noidung"})

                        </div>
                    </div>

                    <div class="form-group">
                        <label for="tac_gia"><b>Tác giả</b></label>
                        <div class="form-actions no-color">
                            @Html.EditorFor(model => model.TAC_GIA, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TAC_GIA, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="seo_title"><b>Keyword</b></label>
                        <div class="form-actions no-color">
                            @Html.EditorFor(model => model.SEO_TITLE, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.SEO_TITLE, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="hinh_anh"><b>Hình ảnh</b></label>
                        <div class="col-md-4">
                            <input class="form-control" type="file" name="Picture" id="IMG" onchange="readPicture(this)" accept="image/jpeg,image/gif,image/png" />
                            <br />
                            <img id="Picture" style="height: 250px; width: 250px; object-fit: contain; border: 3px solid #0af; background-color: #000000" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-2">
                            <button type="submit" class="button" style="vertical-align:middle"><span>Thêm mới</span></button>
                        </div>
                        <div class="col-md-4">
                            <a class="button" style="background-color: rgb(157 154 154 / 44%); color: black" href="@Url.Action("Index")">Quay lại</a>

                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->
</div>

<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

<script>
    tinymce.init({
        selector: 'textarea#MotaSP',
        menubar: false
    });
    function readPicture(input) {
        if (input.files && input.files[0])
            var reader = new FileReader();
        reader.onload = function (e) {
            $('img#Picture').attr('src', e.target.result)
        };
        reader.readAsDataURL(input.files[0])
    }
</script>
<script src="@Url.Content("~/Content/assets-ad/libs/jquery/dist/jquery.min.js")"></script>
<script type="text/javascript">
    $(document).ready(() => {
        new nicEditor().panelInstance('area1')
    })
</script>

VanLangDoctor/VanLangDoctor/Areas/Admin/Views/QL_TinTuc/Delete.cshtml
@model VanLangDoctor.Models.TIN_TUC

@{
    ViewBag.Title = "Xóa bài viết";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/up.css" rel="stylesheet" />
</head>
<body>
    <div class="page-wrapper" style="display: block;">
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-7 align-self-center">
                    <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">@ViewBag.Title</h4>
                    <div class="d-flex align-items-center">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb m-0 p-0">
                                <li class="breadcrumb-item"><a href="~/trang-chu-quan-ly" class="text-muted">Trang chủ</a></li>
                                <li class="breadcrumb-item"><a href="@Url.Action("Index")" class="text-muted">Tin tức</a></li>
                                <li class="breadcrumb-item text-muted active" aria-current="page">@ViewBag.Title</li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <div class="col-5 align-self-center">
                    <div class="customize-input float-right">
                        <a class="button-back" href="@Url.Action("Index")">
                            <span-back>Trở về</span-back>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="card card-body col-md-9">
                    <h3 class="card-title">Bạn chắc chắn muốn xóa thuốc @Html.DisplayFor(model => model.TEN_BAI_VIET) ?</h3>
                    <p class="text-muted font-14 mb-3">
                    </p>
                    <div class="alert alert-success">
                        <div class="dl-horizontal">
                            <div class="row">
                                <h4 class="col-md-3">Tên bài viết: </h4>
                                <span class="col-md-9">@Html.DisplayFor(model => model.TEN_BAI_VIET)</span>
                            </div>

                            <div class="row">
                                <h4 class="col-md-3">Ngày đăng: </h4>
                                <span class="col-md-4">@Html.DisplayFor(model => model.NGAY_DANG)</span>
                            </div>

                            <div class="row">
                                <h4 class="col-md-3">Tác giả: </h4>
                                <span class="col-md-9">@Model.TAC_GIA</span>
                            </div>

                            <div class="row">
                                <h4 class="col-md-3">Keyword: </h4>
                                <span class="col-md-9">@Model.SEO_TITLE</span>
                            </div>

                            <div class="row">
                                <h4 class="col-md-3">Nội dung: </h4>
                                <span style="width: 500px; text-overflow: ellipsis; overflow: hidden; white-space: nowrap;" class="col-md-9">@MvcHtmlString.Create(Model.NOI_DUNG).ToString()</span>
                            </div>

                        </div>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <button type="submit" class="button" style="position: relative; background-color: #FF0000 "><span>Xóa </span></button>
                            </div>
                        }
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card">
                        <div class="card-body" style="text-align:center">
                            <h4 class="card-title">Hình ảnh</h4>
                            <link href="~/Content/uploadavt.css" rel="stylesheet" />
                            <main>
                                <div id="preview">
                                    <div id="view-img"><img src="@Url.Action("Picture", new {Model.ID_TIN_TUC})" style="height: 200px; width: 200px; object-fit:contain; border-radius: 50%; border: 3px solid #0af; background-color:#000000" /></div>
                                </div>
                            </main>
                            <script src="~/Scripts/uploadavt.js"></script>
                        </div> <!-- end card-body-->
                    </div> <!-- end card-->
                </div>
            </div>
        </div>

    </div>
</body>
</html>

VanLangDoctor/VanLangDoctor/Areas/Admin/Views/QL_TinTuc/Edit.cshtml
@model VanLangDoctor.Models.TIN_TUC

@{
    ViewBag.Title = "Cập nhật tin tức";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div id="main-wrapper" data-theme="light" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
     data-sidebar-position="fixed" data-header-position="fixed" data-boxed-layout="full">

    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-7 align-self-center">
                    <h3 class="page-title text-truncate text-dark font-weight-medium mb-1">Xin chào</h3>
                    <div class="d-flex align-items-center">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb m-0 p-0">
                                <li class="breadcrumb-item">
                                    <a href="@Url.Action("Index", "QL_TinTuc")">Thông tin tin tức</a>
                                </li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <div class="container">
                <h1>Tin Tức</h1>
                <p>Thông tin chi tiết của tin tức</p>
                <hr>
                @using (Html.BeginForm("Edit", "QL_TinTuc", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.ID_TIN_TUC)

                        <div class="form-group">
                            <label for="ten_bai_viet"><b>Tên bài viết</b></label>
                            <div class="form-actions no-color">
                                @Html.EditorFor(model => model.TEN_BAI_VIET, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TEN_BAI_VIET, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="ngay_dang"><b>Ngày đăng</b></label>
                            <div class="form-actions no-color">
                                @Html.EditorFor(model => model.NGAY_DANG, new { htmlAttributes = new { @class = "form-control", @readonly = true} })
                                @Html.ValidationMessageFor(model => model.NGAY_DANG, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="noi_dung"><b>Nội dung</b></label>
                            <div class="form-actions no-color">
                                @Html.TextAreaFor(m => m.NOI_DUNG, new { @class = "form-control", @id = "area1" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="tac_gia"><b>Tác giả</b></label>
                            <div class="form-actions no-color">
                                @Html.EditorFor(model => model.TAC_GIA, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TAC_GIA, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="seo_title"><b>Keyword</b></label>
                            <div class="form-actions no-color">
                                @Html.EditorFor(model => model.SEO_TITLE, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.SEO_TITLE, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="hinh_anh"><b>Hình ảnh</b></label>
                            <div class="col-md-4">
                                <input class="form-control" type="file" name="Picture" id="IMG" onchange="readPicture(this)" accept="image/jpeg,image/gif,image/png" />
                                <br />
                                <img id="Picture" src="@Url.Action("Picture","QL_TinTuc", new {Model.ID_TIN_TUC})" style="height: 250px; width: 250px; object-fit: contain; border: 3px solid #0af; background-color: #000000" />
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-2">
                                <button type="submit" class="button" style="vertical-align:middle"><span>Cập nhật</span></button>
                            </div>
                            <div class="col-md-4">
                                <a class="button" style="background-color: rgb(157 154 154 / 44%); color: black" href="@Url.Action("Index")">Quay lại</a>

                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<script>
    function readPicture(input) {
        if (input.files && input.files[0])
            var reader = new FileReader();
        reader.onload = function (e) {
            $('img#Picture').attr('src', e.target.result)
        };
        reader.readAsDataURL(input.files[0])
    }
</script>
<script src="@Url.Content("~/Content/assets-ad/libs/jquery/dist/jquery.min.js")"></script>
<script type="text/javascript">
    $(document).ready(() => {
        new nicEditor().panelInstance('area1')
    })
</script>

VanLangDoctor/VanLangDoctor/Areas/Admin/Views/QL_TinTuc/Index.cshtml
@model IEnumerable<VanLangDoctor.Models.TIN_TUC>

@{
    ViewBag.Title = "Tin tức";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/dist-ad/css/style.min.css" rel="stylesheet">

<div class="page-wrapper" style="display: block">
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-7 align-self-center">
                <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">@ViewBag.Title</h4>
                <div class="d-flex align-items-center">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb m-0 p-0">
                            <li class="breadcrumb-item"><a href="/trang-chu-quan-ly" class="text-muted">Trang chủ</a></li>
                            <li class="breadcrumb-item text-muted active" aria-current="page">@ViewBag.Title</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <div class="col-5 align-self-center">
                <div class="customize-input float-right">
                    <a class="button-plus" href="@Url.Action("Create", "QL_TinTuc")">
                        <span>Đăng tin mới</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            @if (TempData["Success"] != null)
                            {
                                <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert" id="successMessage">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true" style=" float: right; margin-top: -10px">×</span>
                                    </button>
                                    <strong>@TempData["Success"]</strong>
                                </div>
                            }
                            <table id="zero_config" class="table table-striped table-bordered no-wrap">
                                <tr>
                                    <th>Hình ảnh</th>

                                    <th>Tên bài viết</th>

                                    <th>Ngày đăng</th>

                                    <th>Nội dung</th>

                                    <th>Tác giả</th>

                                    <th>SEO TITLE</th>

                                    <th></th>
                                </tr>

                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            <img src="@Url.Action("Picture", new {item.ID_TIN_TUC})" width="50" height="48" />
                                        </td>
                                        <td>
                                            @item.TEN_BAI_VIET
                                        </td>
                                        <td>
                                            @Html.FormatValue(item.NGAY_DANG, "{0:d}")
                                        </td>
                                        <td>
                                            @if (item.NOI_DUNG.Length < 50)
                                            {
                                                @item.NOI_DUNG
                                            }
                                            else
                                            {
                                                @item.NOI_DUNG.Substring(0, 50).ToString() <span>...</span>
                                            }
                                        </td>
                                        <td>
                                            @item.TAC_GIA
                                        </td>
                                        <td>
                                            @item.SEO_TITLE
                                        </td>
                                        <td>
                                            <a href="@Url.Action("Edit","QL_TinTuc", new { id = item.ID_TIN_TUC })"><i class="ti-pencil"></i></a>
                                            <a href="@Url.Action("Delete","QL_TinTuc", new { id = item.ID_TIN_TUC })"><i class="ti-trash"></i></a>
                                        </td>
                                    </tr>
                                }

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>